#!/usr/bin/env bash
# Asserts that `dart format` is actually using THIS project's formatter
# configuration — concretely, that `trailing_commas: preserve` is in effect.
#
# Why this script exists (backlog A-7):
#
#   `preserve` is not set in our own analysis_options.yaml. It comes from
#   `include: package:very_good_analysis/analysis_options.yaml`, so it needs
#   package resolution — i.e. a `.dart_tool/package_config.json`. A fresh
#   `git worktree` has none. `dart format` then prints "Package resolution
#   error" to *stderr*, EXITS 0, and silently falls back to the formatter
#   default `trailing_commas: automate`, rewriting ~93 of 255 files: trailing
#   commas stripped, multi-line calls rejoined.
#
#   The reason that is a hazard and not a nuisance: `preserve` is *stable* on
#   `automate`'s output. So `dart format --set-exit-if-changed` PASSES on the
#   churn, and neither the pre-commit hook nor ci.yml can detect it after the
#   fact. In wave 4 one agent put 85 out-of-scope files into a branch this way,
#   two of them being concurrently edited by other agents.
#
#   It cannot be fixed by checked-in config: an unresolvable `package:` include
#   makes `dart format` discard the WHOLE options file, so an explicit
#   `formatter:` block next to the failing include is dropped with it. Measured
#   four ways; see docs/plans/2026-08-28-formatter-trap.md.
#
# Usage:
#   tool/check_formatter_config.sh
#
# Run it in any fresh worktree BEFORE `dart format`. It is also wired into
# lefthook's pre-commit `format` job and into ci.yml. Exit 0 = safe to format.

set -euo pipefail

# Root from this script's own location, the same way tool/e2e.sh does it —
# NOT `git rev-parse`, which is unreliable when a git hook has set GIT_DIR.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# `env -u GIT_DIR -u GIT_INDEX_FILE`: git sets these for hook subprocesses so
# that its own commands touch the right worktree/index, but the Dart/Flutter
# tool shells out to git too (to read its own SDK version) and inherits them
# unchanged — GIT_DIR then points at Flutter's SDK checkout, the version reads
# back 0.0.0-unknown, and dependency resolution fails. Same reasoning as
# lefthook.yml's `analyze` job. Unset both before invoking dart.
DART=(env -u GIT_DIR -u GIT_INDEX_FILE dart)

# The probe. Under `trailing_commas: preserve` the trailing comma keeps this
# split across lines, so the file is already formatted. Under `automate` the
# comma is dropped and it collapses onto one line. That difference IS the
# check: exit 0 vs exit 1, no output parsing.
#
# Deliberately NOT a committed file. It is regenerated on every run inside
# .dart_tool/, which is gitignored (so it can never reach a branch) and which
# `dart format .`, `flutter analyze` and `flutter test` all skip, because
# their directory traversal ignores dot-directories. That is what stops a
# future tool run from "helpfully" reformatting the probe and disarming it.
# It has to live inside the repo tree, though — anywhere else and `dart
# format` would walk up and find neither analysis_options.yaml nor
# package_config.json, and report a false alarm.
write_probe() {
  cat >"$1" <<'DART'
// Generated by tool/check_formatter_config.sh on every run. Not committed.
// Formatting differs between trailing_commas: preserve (stays split) and
// automate (collapses to one line) — that is the whole point.
final probe = <int>[
  1,
  2,
];
DART
}

# 0 = the formatter leaves the probe alone, 1 = it would rewrite it.
probe_is_stable() {
  "${DART[@]}" format --output=none --set-exit-if-changed "$1" >/dev/null 2>&1
}

# ---------------------------------------------------------------------------
# 1. Self-test, so this check can never pass vacuously.
#
# The entire bug class here is "a check that stays green while the bug is
# live", so first prove the probe still tells the two modes apart: format the
# SAME fixture in a throwaway directory that pins `automate`, and require that
# it DOES change there. Pinning the mode explicitly (rather than relying on
# "no options file found" and the SDK's default) keeps this independent of
# both the SDK default and any stray ambient analysis_options.yaml.
# ---------------------------------------------------------------------------
selftest_dir="$(mktemp -d)"
trap 'rm -rf "$selftest_dir"' EXIT

cat >"$selftest_dir/analysis_options.yaml" <<'YAML'
formatter:
  trailing_commas: automate
YAML
write_probe "$selftest_dir/probe.dart"

if probe_is_stable "$selftest_dir/probe.dart"; then
  cat >&2 <<'MSG'
check_formatter_config: SELF-TEST FAILED — this check has gone vacuous.

The probe fixture no longer formats differently under `trailing_commas:
preserve` than under `automate`, so a passing result would prove nothing.
Do not ignore this: the formatter trap it guards against is undetectable by
CI, so this script is the only thing standing between a fresh worktree and
~93 files of reflow churn.

Fix the probe in write_probe() above so that it is stable under `preserve`
and rewritten under `automate`, then re-run.
MSG
  exit 1
fi

# ---------------------------------------------------------------------------
# 2. The real assertion, in this checkout.
# ---------------------------------------------------------------------------
probe_dir="$ROOT/.dart_tool/formatter_probe"
mkdir -p "$probe_dir"
write_probe "$probe_dir/probe.dart"

if probe_is_stable "$probe_dir/probe.dart"; then
  echo "check_formatter_config: OK — trailing_commas: preserve is in effect."
  exit 0
fi

# Failed. Re-run to capture the diagnostic dart format only writes to stderr.
stderr="$("${DART[@]}" format --output=none "$probe_dir/probe.dart" 2>&1 >/dev/null || true)"

cat >&2 <<'MSG'
check_formatter_config: FAILED — `dart format` is NOT using this project's
formatter configuration. `trailing_commas: preserve` is not in effect.

DO NOT RUN `dart format` IN THIS CHECKOUT until this is fixed. It would strip
trailing commas and rejoin multi-line calls across roughly 93 of 255 files,
and you would not be warned: the fallback mode's output is stable under
`preserve`, so `--set-exit-if-changed` passes on the churn afterwards and
neither the pre-commit hook nor CI can see it. That is how 85 out-of-scope
files landed in a branch in wave 4.

Almost always the cause is a fresh `git worktree` with no `.dart_tool/`, which
leaves the `package:very_good_analysis/...` include in analysis_options.yaml
unresolvable. Fix:

    env -u GIT_DIR -u GIT_INDEX_FILE flutter pub get --enforce-lockfile

(or copy `.dart_tool/package_config.json` in from the primary checkout — it is
gitignored, so it can never be committed). Then re-run this script.

If `.dart_tool/package_config.json` is present and this still fails, the
configuration itself has drifted: check that analysis_options.yaml still
reaches very_good_analysis and that nothing overrides `formatter:
trailing_commas`. See docs/plans/2026-08-28-formatter-trap.md and backlog A-7.
MSG

if [[ -n "$stderr" ]]; then
  echo >&2
  echo "What dart format said (stderr only — it still exits 0):" >&2
  printf '%s\n' "$stderr" | sed 's/^/    /' >&2
fi

exit 1
